/*
 * Copyright 2019 Rackspace US, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry-edge.proto

package telemetry_edge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgentType int32

const (
	AgentType_TELEGRAF AgentType = 0
	AgentType_FILEBEAT AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "TELEGRAF",
	1: "FILEBEAT",
}

var AgentType_value = map[string]int32{
	"TELEGRAF": 0,
	"FILEBEAT": 1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{0}
}

type Checksum_Type int32

const (
	Checksum_SHA256 Checksum_Type = 0
	Checksum_SHA512 Checksum_Type = 1
)

var Checksum_Type_name = map[int32]string{
	0: "SHA256",
	1: "SHA512",
}

var Checksum_Type_value = map[string]int32{
	"SHA256": 0,
	"SHA512": 1,
}

func (x Checksum_Type) String() string {
	return proto.EnumName(Checksum_Type_name, int32(x))
}

func (Checksum_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{5, 0}
}

type ConfigurationOp_Type int32

const (
	ConfigurationOp_CREATE ConfigurationOp_Type = 0
	ConfigurationOp_MODIFY ConfigurationOp_Type = 1
	ConfigurationOp_REMOVE ConfigurationOp_Type = 2
)

var ConfigurationOp_Type_name = map[int32]string{
	0: "CREATE",
	1: "MODIFY",
	2: "REMOVE",
}

var ConfigurationOp_Type_value = map[string]int32{
	"CREATE": 0,
	"MODIFY": 1,
	"REMOVE": 2,
}

func (x ConfigurationOp_Type) String() string {
	return proto.EnumName(ConfigurationOp_Type_name, int32(x))
}

func (ConfigurationOp_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{7, 0}
}

type EnvoySummary struct {
	Version              string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SupportedAgents      []AgentType       `protobuf:"varint,2,rep,packed,name=supportedAgents,proto3,enum=AgentType" json:"supportedAgents,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ResourceId           string            `protobuf:"bytes,4,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	Zone                 string            `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EnvoySummary) Reset()         { *m = EnvoySummary{} }
func (m *EnvoySummary) String() string { return proto.CompactTextString(m) }
func (*EnvoySummary) ProtoMessage()    {}
func (*EnvoySummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{0}
}

func (m *EnvoySummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoySummary.Unmarshal(m, b)
}
func (m *EnvoySummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoySummary.Marshal(b, m, deterministic)
}
func (m *EnvoySummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoySummary.Merge(m, src)
}
func (m *EnvoySummary) XXX_Size() int {
	return xxx_messageInfo_EnvoySummary.Size(m)
}
func (m *EnvoySummary) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoySummary.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoySummary proto.InternalMessageInfo

func (m *EnvoySummary) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *EnvoySummary) GetSupportedAgents() []AgentType {
	if m != nil {
		return m.SupportedAgents
	}
	return nil
}

func (m *EnvoySummary) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *EnvoySummary) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *EnvoySummary) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type Agent struct {
	Type                 AgentType `protobuf:"varint,1,opt,name=type,proto3,enum=AgentType" json:"type,omitempty"`
	Version              string    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{1}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_TELEGRAF
}

func (m *Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type EnvoyInstruction struct {
	// Types that are valid to be assigned to Details:
	//	*EnvoyInstruction_Install
	//	*EnvoyInstruction_Configure
	//	*EnvoyInstruction_Refresh
	//	*EnvoyInstruction_TestMonitor
	Details              isEnvoyInstruction_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EnvoyInstruction) Reset()         { *m = EnvoyInstruction{} }
func (m *EnvoyInstruction) String() string { return proto.CompactTextString(m) }
func (*EnvoyInstruction) ProtoMessage()    {}
func (*EnvoyInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{2}
}

func (m *EnvoyInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyInstruction.Unmarshal(m, b)
}
func (m *EnvoyInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyInstruction.Marshal(b, m, deterministic)
}
func (m *EnvoyInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyInstruction.Merge(m, src)
}
func (m *EnvoyInstruction) XXX_Size() int {
	return xxx_messageInfo_EnvoyInstruction.Size(m)
}
func (m *EnvoyInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyInstruction proto.InternalMessageInfo

type isEnvoyInstruction_Details interface {
	isEnvoyInstruction_Details()
}

type EnvoyInstruction_Install struct {
	Install *EnvoyInstructionInstall `protobuf:"bytes,1,opt,name=install,proto3,oneof"`
}

type EnvoyInstruction_Configure struct {
	Configure *EnvoyInstructionConfigure `protobuf:"bytes,2,opt,name=configure,proto3,oneof"`
}

type EnvoyInstruction_Refresh struct {
	Refresh *EnvoyInstructionRefresh `protobuf:"bytes,3,opt,name=refresh,proto3,oneof"`
}

type EnvoyInstruction_TestMonitor struct {
	TestMonitor *EnvoyInstructionTestMonitor `protobuf:"bytes,4,opt,name=testMonitor,proto3,oneof"`
}

func (*EnvoyInstruction_Install) isEnvoyInstruction_Details() {}

func (*EnvoyInstruction_Configure) isEnvoyInstruction_Details() {}

func (*EnvoyInstruction_Refresh) isEnvoyInstruction_Details() {}

func (*EnvoyInstruction_TestMonitor) isEnvoyInstruction_Details() {}

func (m *EnvoyInstruction) GetDetails() isEnvoyInstruction_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *EnvoyInstruction) GetInstall() *EnvoyInstructionInstall {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Install); ok {
		return x.Install
	}
	return nil
}

func (m *EnvoyInstruction) GetConfigure() *EnvoyInstructionConfigure {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Configure); ok {
		return x.Configure
	}
	return nil
}

func (m *EnvoyInstruction) GetRefresh() *EnvoyInstructionRefresh {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Refresh); ok {
		return x.Refresh
	}
	return nil
}

func (m *EnvoyInstruction) GetTestMonitor() *EnvoyInstructionTestMonitor {
	if x, ok := m.GetDetails().(*EnvoyInstruction_TestMonitor); ok {
		return x.TestMonitor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EnvoyInstruction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EnvoyInstruction_Install)(nil),
		(*EnvoyInstruction_Configure)(nil),
		(*EnvoyInstruction_Refresh)(nil),
		(*EnvoyInstruction_TestMonitor)(nil),
	}
}

// DetachedInstructions is used for offline, detached loading of instructions from a file.
type DetachedInstructions struct {
	Instructions         []*EnvoyInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DetachedInstructions) Reset()         { *m = DetachedInstructions{} }
func (m *DetachedInstructions) String() string { return proto.CompactTextString(m) }
func (*DetachedInstructions) ProtoMessage()    {}
func (*DetachedInstructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{3}
}

func (m *DetachedInstructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachedInstructions.Unmarshal(m, b)
}
func (m *DetachedInstructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachedInstructions.Marshal(b, m, deterministic)
}
func (m *DetachedInstructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachedInstructions.Merge(m, src)
}
func (m *DetachedInstructions) XXX_Size() int {
	return xxx_messageInfo_DetachedInstructions.Size(m)
}
func (m *DetachedInstructions) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachedInstructions.DiscardUnknown(m)
}

var xxx_messageInfo_DetachedInstructions proto.InternalMessageInfo

func (m *DetachedInstructions) GetInstructions() []*EnvoyInstruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type EnvoyInstructionInstall struct {
	Agent    *Agent    `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Url      string    `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Checksum *Checksum `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// path to the agent's executable within the package
	Exe                  string   `protobuf:"bytes,4,opt,name=exe,proto3" json:"exe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvoyInstructionInstall) Reset()         { *m = EnvoyInstructionInstall{} }
func (m *EnvoyInstructionInstall) String() string { return proto.CompactTextString(m) }
func (*EnvoyInstructionInstall) ProtoMessage()    {}
func (*EnvoyInstructionInstall) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{4}
}

func (m *EnvoyInstructionInstall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyInstructionInstall.Unmarshal(m, b)
}
func (m *EnvoyInstructionInstall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyInstructionInstall.Marshal(b, m, deterministic)
}
func (m *EnvoyInstructionInstall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyInstructionInstall.Merge(m, src)
}
func (m *EnvoyInstructionInstall) XXX_Size() int {
	return xxx_messageInfo_EnvoyInstructionInstall.Size(m)
}
func (m *EnvoyInstructionInstall) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyInstructionInstall.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyInstructionInstall proto.InternalMessageInfo

func (m *EnvoyInstructionInstall) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *EnvoyInstructionInstall) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EnvoyInstructionInstall) GetChecksum() *Checksum {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *EnvoyInstructionInstall) GetExe() string {
	if m != nil {
		return m.Exe
	}
	return ""
}

type Checksum struct {
	Value                string        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 Checksum_Type `protobuf:"varint,2,opt,name=type,proto3,enum=Checksum_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Checksum) Reset()         { *m = Checksum{} }
func (m *Checksum) String() string { return proto.CompactTextString(m) }
func (*Checksum) ProtoMessage()    {}
func (*Checksum) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{5}
}

func (m *Checksum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checksum.Unmarshal(m, b)
}
func (m *Checksum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checksum.Marshal(b, m, deterministic)
}
func (m *Checksum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checksum.Merge(m, src)
}
func (m *Checksum) XXX_Size() int {
	return xxx_messageInfo_Checksum.Size(m)
}
func (m *Checksum) XXX_DiscardUnknown() {
	xxx_messageInfo_Checksum.DiscardUnknown(m)
}

var xxx_messageInfo_Checksum proto.InternalMessageInfo

func (m *Checksum) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Checksum) GetType() Checksum_Type {
	if m != nil {
		return m.Type
	}
	return Checksum_SHA256
}

type EnvoyInstructionConfigure struct {
	AgentType            AgentType          `protobuf:"varint,1,opt,name=agentType,proto3,enum=AgentType" json:"agentType,omitempty"`
	Operations           []*ConfigurationOp `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EnvoyInstructionConfigure) Reset()         { *m = EnvoyInstructionConfigure{} }
func (m *EnvoyInstructionConfigure) String() string { return proto.CompactTextString(m) }
func (*EnvoyInstructionConfigure) ProtoMessage()    {}
func (*EnvoyInstructionConfigure) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{6}
}

func (m *EnvoyInstructionConfigure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyInstructionConfigure.Unmarshal(m, b)
}
func (m *EnvoyInstructionConfigure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyInstructionConfigure.Marshal(b, m, deterministic)
}
func (m *EnvoyInstructionConfigure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyInstructionConfigure.Merge(m, src)
}
func (m *EnvoyInstructionConfigure) XXX_Size() int {
	return xxx_messageInfo_EnvoyInstructionConfigure.Size(m)
}
func (m *EnvoyInstructionConfigure) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyInstructionConfigure.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyInstructionConfigure proto.InternalMessageInfo

func (m *EnvoyInstructionConfigure) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_TELEGRAF
}

func (m *EnvoyInstructionConfigure) GetOperations() []*ConfigurationOp {
	if m != nil {
		return m.Operations
	}
	return nil
}

type ConfigurationOp struct {
	Id       string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision string               `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Type     ConfigurationOp_Type `protobuf:"varint,3,opt,name=type,proto3,enum=ConfigurationOp_Type" json:"type,omitempty"`
	Content  string               `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// conveys extra labels/tags that should be associated with the generated measurements
	ExtraLabels map[string]string `protobuf:"bytes,5,rep,name=extraLabels,proto3" json:"extraLabels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// monitoring interval, in seconds, value of 0 means use default
	Interval             int64    `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationOp) Reset()         { *m = ConfigurationOp{} }
func (m *ConfigurationOp) String() string { return proto.CompactTextString(m) }
func (*ConfigurationOp) ProtoMessage()    {}
func (*ConfigurationOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{7}
}

func (m *ConfigurationOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationOp.Unmarshal(m, b)
}
func (m *ConfigurationOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationOp.Marshal(b, m, deterministic)
}
func (m *ConfigurationOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationOp.Merge(m, src)
}
func (m *ConfigurationOp) XXX_Size() int {
	return xxx_messageInfo_ConfigurationOp.Size(m)
}
func (m *ConfigurationOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationOp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationOp proto.InternalMessageInfo

func (m *ConfigurationOp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigurationOp) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ConfigurationOp) GetType() ConfigurationOp_Type {
	if m != nil {
		return m.Type
	}
	return ConfigurationOp_CREATE
}

func (m *ConfigurationOp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ConfigurationOp) GetExtraLabels() map[string]string {
	if m != nil {
		return m.ExtraLabels
	}
	return nil
}

func (m *ConfigurationOp) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

// mainly used to test the ambassador->envoy liveness of the channel, but could eventually
// contain the full set of instructions of ensure consistency
type EnvoyInstructionRefresh struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvoyInstructionRefresh) Reset()         { *m = EnvoyInstructionRefresh{} }
func (m *EnvoyInstructionRefresh) String() string { return proto.CompactTextString(m) }
func (*EnvoyInstructionRefresh) ProtoMessage()    {}
func (*EnvoyInstructionRefresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{8}
}

func (m *EnvoyInstructionRefresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyInstructionRefresh.Unmarshal(m, b)
}
func (m *EnvoyInstructionRefresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyInstructionRefresh.Marshal(b, m, deterministic)
}
func (m *EnvoyInstructionRefresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyInstructionRefresh.Merge(m, src)
}
func (m *EnvoyInstructionRefresh) XXX_Size() int {
	return xxx_messageInfo_EnvoyInstructionRefresh.Size(m)
}
func (m *EnvoyInstructionRefresh) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyInstructionRefresh.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyInstructionRefresh proto.InternalMessageInfo

type KeepAliveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{9}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

type KeepAliveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{10}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

type LogEvent struct {
	AgentType            AgentType `protobuf:"varint,1,opt,name=agentType,proto3,enum=AgentType" json:"agentType,omitempty"`
	JsonContent          string    `protobuf:"bytes,2,opt,name=jsonContent,proto3" json:"jsonContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogEvent) Reset()         { *m = LogEvent{} }
func (m *LogEvent) String() string { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()    {}
func (*LogEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{11}
}

func (m *LogEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEvent.Unmarshal(m, b)
}
func (m *LogEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEvent.Marshal(b, m, deterministic)
}
func (m *LogEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEvent.Merge(m, src)
}
func (m *LogEvent) XXX_Size() int {
	return xxx_messageInfo_LogEvent.Size(m)
}
func (m *LogEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LogEvent proto.InternalMessageInfo

func (m *LogEvent) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_TELEGRAF
}

func (m *LogEvent) GetJsonContent() string {
	if m != nil {
		return m.JsonContent
	}
	return ""
}

type PostLogEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostLogEventResponse) Reset()         { *m = PostLogEventResponse{} }
func (m *PostLogEventResponse) String() string { return proto.CompactTextString(m) }
func (*PostLogEventResponse) ProtoMessage()    {}
func (*PostLogEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{12}
}

func (m *PostLogEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLogEventResponse.Unmarshal(m, b)
}
func (m *PostLogEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLogEventResponse.Marshal(b, m, deterministic)
}
func (m *PostLogEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLogEventResponse.Merge(m, src)
}
func (m *PostLogEventResponse) XXX_Size() int {
	return xxx_messageInfo_PostLogEventResponse.Size(m)
}
func (m *PostLogEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLogEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostLogEventResponse proto.InternalMessageInfo

type PostedMetric struct {
	Metric               *Metric  `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostedMetric) Reset()         { *m = PostedMetric{} }
func (m *PostedMetric) String() string { return proto.CompactTextString(m) }
func (*PostedMetric) ProtoMessage()    {}
func (*PostedMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{13}
}

func (m *PostedMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostedMetric.Unmarshal(m, b)
}
func (m *PostedMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostedMetric.Marshal(b, m, deterministic)
}
func (m *PostedMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostedMetric.Merge(m, src)
}
func (m *PostedMetric) XXX_Size() int {
	return xxx_messageInfo_PostedMetric.Size(m)
}
func (m *PostedMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PostedMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PostedMetric proto.InternalMessageInfo

func (m *PostedMetric) GetMetric() *Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

type Metric struct {
	// Types that are valid to be assigned to Variant:
	//	*Metric_NameTagValue
	Variant              isMetric_Variant `protobuf_oneof:"variant"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{14}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

type isMetric_Variant interface {
	isMetric_Variant()
}

type Metric_NameTagValue struct {
	NameTagValue *NameTagValueMetric `protobuf:"bytes,1,opt,name=nameTagValue,proto3,oneof"`
}

func (*Metric_NameTagValue) isMetric_Variant() {}

func (m *Metric) GetVariant() isMetric_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (m *Metric) GetNameTagValue() *NameTagValueMetric {
	if x, ok := m.GetVariant().(*Metric_NameTagValue); ok {
		return x.NameTagValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metric_NameTagValue)(nil),
	}
}

type NameTagValueMetric struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// in milliseconds
	Timestamp            int64              `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags                 map[string]string  `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Fvalues              map[string]float64 `protobuf:"bytes,4,rep,name=fvalues,proto3" json:"fvalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Svalues              map[string]string  `protobuf:"bytes,5,rep,name=svalues,proto3" json:"svalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ivalues              map[string]int64   `protobuf:"bytes,6,rep,name=ivalues,proto3" json:"ivalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NameTagValueMetric) Reset()         { *m = NameTagValueMetric{} }
func (m *NameTagValueMetric) String() string { return proto.CompactTextString(m) }
func (*NameTagValueMetric) ProtoMessage()    {}
func (*NameTagValueMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{15}
}

func (m *NameTagValueMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameTagValueMetric.Unmarshal(m, b)
}
func (m *NameTagValueMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameTagValueMetric.Marshal(b, m, deterministic)
}
func (m *NameTagValueMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameTagValueMetric.Merge(m, src)
}
func (m *NameTagValueMetric) XXX_Size() int {
	return xxx_messageInfo_NameTagValueMetric.Size(m)
}
func (m *NameTagValueMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_NameTagValueMetric.DiscardUnknown(m)
}

var xxx_messageInfo_NameTagValueMetric proto.InternalMessageInfo

func (m *NameTagValueMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameTagValueMetric) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NameTagValueMetric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *NameTagValueMetric) GetFvalues() map[string]float64 {
	if m != nil {
		return m.Fvalues
	}
	return nil
}

func (m *NameTagValueMetric) GetSvalues() map[string]string {
	if m != nil {
		return m.Svalues
	}
	return nil
}

func (m *NameTagValueMetric) GetIvalues() map[string]int64 {
	if m != nil {
		return m.Ivalues
	}
	return nil
}

type PostMetricResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMetricResponse) Reset()         { *m = PostMetricResponse{} }
func (m *PostMetricResponse) String() string { return proto.CompactTextString(m) }
func (*PostMetricResponse) ProtoMessage()    {}
func (*PostMetricResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{16}
}

func (m *PostMetricResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMetricResponse.Unmarshal(m, b)
}
func (m *PostMetricResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMetricResponse.Marshal(b, m, deterministic)
}
func (m *PostMetricResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMetricResponse.Merge(m, src)
}
func (m *PostMetricResponse) XXX_Size() int {
	return xxx_messageInfo_PostMetricResponse.Size(m)
}
func (m *PostMetricResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMetricResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMetricResponse proto.InternalMessageInfo

type EnvoyInstructionTestMonitor struct {
	CorrelationId string    `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	AgentType     AgentType `protobuf:"varint,2,opt,name=agentType,proto3,enum=AgentType" json:"agentType,omitempty"`
	Content       string    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// declares the maximum amount of time in seconds the test operation can run
	Timeout              int64    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvoyInstructionTestMonitor) Reset()         { *m = EnvoyInstructionTestMonitor{} }
func (m *EnvoyInstructionTestMonitor) String() string { return proto.CompactTextString(m) }
func (*EnvoyInstructionTestMonitor) ProtoMessage()    {}
func (*EnvoyInstructionTestMonitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{17}
}

func (m *EnvoyInstructionTestMonitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvoyInstructionTestMonitor.Unmarshal(m, b)
}
func (m *EnvoyInstructionTestMonitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvoyInstructionTestMonitor.Marshal(b, m, deterministic)
}
func (m *EnvoyInstructionTestMonitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvoyInstructionTestMonitor.Merge(m, src)
}
func (m *EnvoyInstructionTestMonitor) XXX_Size() int {
	return xxx_messageInfo_EnvoyInstructionTestMonitor.Size(m)
}
func (m *EnvoyInstructionTestMonitor) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvoyInstructionTestMonitor.DiscardUnknown(m)
}

var xxx_messageInfo_EnvoyInstructionTestMonitor proto.InternalMessageInfo

func (m *EnvoyInstructionTestMonitor) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *EnvoyInstructionTestMonitor) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_TELEGRAF
}

func (m *EnvoyInstructionTestMonitor) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *EnvoyInstructionTestMonitor) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type TestMonitorResults struct {
	CorrelationId        string    `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Errors               []string  `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TestMonitorResults) Reset()         { *m = TestMonitorResults{} }
func (m *TestMonitorResults) String() string { return proto.CompactTextString(m) }
func (*TestMonitorResults) ProtoMessage()    {}
func (*TestMonitorResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{18}
}

func (m *TestMonitorResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMonitorResults.Unmarshal(m, b)
}
func (m *TestMonitorResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMonitorResults.Marshal(b, m, deterministic)
}
func (m *TestMonitorResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMonitorResults.Merge(m, src)
}
func (m *TestMonitorResults) XXX_Size() int {
	return xxx_messageInfo_TestMonitorResults.Size(m)
}
func (m *TestMonitorResults) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMonitorResults.DiscardUnknown(m)
}

var xxx_messageInfo_TestMonitorResults proto.InternalMessageInfo

func (m *TestMonitorResults) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *TestMonitorResults) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *TestMonitorResults) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type PostTestMonitorResultsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTestMonitorResultsResponse) Reset()         { *m = PostTestMonitorResultsResponse{} }
func (m *PostTestMonitorResultsResponse) String() string { return proto.CompactTextString(m) }
func (*PostTestMonitorResultsResponse) ProtoMessage()    {}
func (*PostTestMonitorResultsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47d201107f106870, []int{19}
}

func (m *PostTestMonitorResultsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTestMonitorResultsResponse.Unmarshal(m, b)
}
func (m *PostTestMonitorResultsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTestMonitorResultsResponse.Marshal(b, m, deterministic)
}
func (m *PostTestMonitorResultsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTestMonitorResultsResponse.Merge(m, src)
}
func (m *PostTestMonitorResultsResponse) XXX_Size() int {
	return xxx_messageInfo_PostTestMonitorResultsResponse.Size(m)
}
func (m *PostTestMonitorResultsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTestMonitorResultsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostTestMonitorResultsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("AgentType", AgentType_name, AgentType_value)
	proto.RegisterEnum("Checksum_Type", Checksum_Type_name, Checksum_Type_value)
	proto.RegisterEnum("ConfigurationOp_Type", ConfigurationOp_Type_name, ConfigurationOp_Type_value)
	proto.RegisterType((*EnvoySummary)(nil), "EnvoySummary")
	proto.RegisterMapType((map[string]string)(nil), "EnvoySummary.LabelsEntry")
	proto.RegisterType((*Agent)(nil), "Agent")
	proto.RegisterType((*EnvoyInstruction)(nil), "EnvoyInstruction")
	proto.RegisterType((*DetachedInstructions)(nil), "DetachedInstructions")
	proto.RegisterType((*EnvoyInstructionInstall)(nil), "EnvoyInstructionInstall")
	proto.RegisterType((*Checksum)(nil), "Checksum")
	proto.RegisterType((*EnvoyInstructionConfigure)(nil), "EnvoyInstructionConfigure")
	proto.RegisterType((*ConfigurationOp)(nil), "ConfigurationOp")
	proto.RegisterMapType((map[string]string)(nil), "ConfigurationOp.ExtraLabelsEntry")
	proto.RegisterType((*EnvoyInstructionRefresh)(nil), "EnvoyInstructionRefresh")
	proto.RegisterType((*KeepAliveRequest)(nil), "KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "KeepAliveResponse")
	proto.RegisterType((*LogEvent)(nil), "LogEvent")
	proto.RegisterType((*PostLogEventResponse)(nil), "PostLogEventResponse")
	proto.RegisterType((*PostedMetric)(nil), "PostedMetric")
	proto.RegisterType((*Metric)(nil), "Metric")
	proto.RegisterType((*NameTagValueMetric)(nil), "NameTagValueMetric")
	proto.RegisterMapType((map[string]float64)(nil), "NameTagValueMetric.FvaluesEntry")
	proto.RegisterMapType((map[string]int64)(nil), "NameTagValueMetric.IvaluesEntry")
	proto.RegisterMapType((map[string]string)(nil), "NameTagValueMetric.SvaluesEntry")
	proto.RegisterMapType((map[string]string)(nil), "NameTagValueMetric.TagsEntry")
	proto.RegisterType((*PostMetricResponse)(nil), "PostMetricResponse")
	proto.RegisterType((*EnvoyInstructionTestMonitor)(nil), "EnvoyInstructionTestMonitor")
	proto.RegisterType((*TestMonitorResults)(nil), "TestMonitorResults")
	proto.RegisterType((*PostTestMonitorResultsResponse)(nil), "PostTestMonitorResultsResponse")
}

func init() { proto.RegisterFile("telemetry-edge.proto", fileDescriptor_47d201107f106870) }

var fileDescriptor_47d201107f106870 = []byte{
	// 1159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xb6, 0xe4, 0xbf, 0xf8, 0xd8, 0x4d, 0x9d, 0x4d, 0x1a, 0x14, 0x13, 0x52, 0x57, 0x03, 0x43,
	0xe8, 0x0c, 0x4b, 0xe3, 0x36, 0x40, 0x73, 0xc1, 0xe0, 0xa4, 0x0a, 0xf1, 0x90, 0x34, 0x1d, 0xc5,
	0x93, 0x19, 0x2e, 0x37, 0xf2, 0xc6, 0x11, 0x91, 0x25, 0xb3, 0xbb, 0x32, 0x35, 0x57, 0x0c, 0x37,
	0xbc, 0x03, 0x77, 0xbc, 0x06, 0x2f, 0xc1, 0x2b, 0x31, 0xbb, 0x5a, 0xd9, 0xf2, 0x4f, 0x42, 0x73,
	0x77, 0xce, 0xd9, 0xf3, 0xed, 0x9e, 0x9f, 0xef, 0x1c, 0x09, 0x36, 0x04, 0x0d, 0xe8, 0x80, 0x0a,
	0x36, 0xfe, 0x92, 0xf6, 0xfa, 0x14, 0x0f, 0x59, 0x24, 0x22, 0xfb, 0x77, 0x13, 0x6a, 0x4e, 0x38,
	0x8a, 0xc6, 0x17, 0xf1, 0x60, 0x40, 0xd8, 0x18, 0x59, 0x50, 0x1e, 0x51, 0xc6, 0xfd, 0x28, 0xb4,
	0x8c, 0xa6, 0xb1, 0x5b, 0x71, 0x53, 0x15, 0xbd, 0x82, 0xc7, 0x3c, 0x1e, 0x0e, 0x23, 0x26, 0x68,
	0xaf, 0xdd, 0xa7, 0xa1, 0xe0, 0x96, 0xd9, 0xcc, 0xef, 0xae, 0xb6, 0x00, 0x2b, 0xb5, 0x3b, 0x1e,
	0x52, 0x77, 0xde, 0x05, 0xed, 0x41, 0x29, 0x20, 0x57, 0x34, 0xe0, 0x56, 0xbe, 0x99, 0xdf, 0xad,
	0xb6, 0xb6, 0x70, 0xf6, 0x39, 0x7c, 0xaa, 0xce, 0x9c, 0x50, 0xb0, 0xb1, 0xab, 0x1d, 0xd1, 0x0e,
	0x00, 0xa3, 0x3c, 0x8a, 0x99, 0x47, 0x3b, 0x3d, 0xab, 0xa0, 0xa2, 0xc8, 0x58, 0x10, 0x82, 0xc2,
	0x6f, 0x51, 0x48, 0xad, 0xa2, 0x3a, 0x51, 0x72, 0xe3, 0x35, 0x54, 0x33, 0x57, 0xa1, 0x3a, 0xe4,
	0x6f, 0xe9, 0x58, 0x67, 0x20, 0x45, 0xb4, 0x01, 0xc5, 0x11, 0x09, 0x62, 0x6a, 0x99, 0xca, 0x96,
	0x28, 0x07, 0xe6, 0xb7, 0x86, 0xdd, 0x86, 0xa2, 0x8a, 0x15, 0xed, 0x40, 0x41, 0x8c, 0x87, 0x54,
	0xa1, 0x66, 0xb3, 0x52, 0xf6, 0x6c, 0x69, 0xcc, 0x99, 0xd2, 0xd8, 0x7f, 0x9a, 0x50, 0x57, 0x69,
	0x75, 0x42, 0x2e, 0x58, 0xec, 0x89, 0xa4, 0x5e, 0x65, 0x3f, 0xe4, 0x82, 0x04, 0x81, 0xba, 0xb1,
	0xda, 0xb2, 0xf0, 0xbc, 0x4f, 0x27, 0x39, 0x3f, 0xc9, 0xb9, 0xa9, 0x2b, 0x3a, 0x80, 0x8a, 0x17,
	0x85, 0xd7, 0x7e, 0x3f, 0x66, 0x49, 0xac, 0xd5, 0x56, 0x63, 0x01, 0x77, 0x94, 0x7a, 0x9c, 0xe4,
	0xdc, 0xa9, 0xbb, 0x7c, 0x91, 0xd1, 0x6b, 0x46, 0xf9, 0x8d, 0x95, 0xbf, 0xe3, 0x45, 0x37, 0x39,
	0x97, 0x2f, 0x6a, 0x57, 0xf4, 0x3d, 0x54, 0x05, 0xe5, 0xe2, 0x2c, 0x0a, 0x7d, 0x11, 0x31, 0x55,
	0xef, 0x6a, 0x6b, 0x7b, 0x01, 0xd9, 0x9d, 0xfa, 0x9c, 0xe4, 0xdc, 0x2c, 0xe4, 0xb0, 0x02, 0xe5,
	0x1e, 0x15, 0xc4, 0x0f, 0xb8, 0x7d, 0x06, 0x1b, 0x6f, 0xa8, 0x20, 0xde, 0x0d, 0xed, 0x65, 0xb0,
	0x1c, 0xed, 0x43, 0xcd, 0xcf, 0xe8, 0x96, 0xa1, 0xc8, 0xb0, 0xb6, 0x18, 0xdf, 0x8c, 0x9b, 0xfd,
	0x87, 0x01, 0x1f, 0xdd, 0x51, 0x34, 0xb4, 0x0d, 0x45, 0x22, 0x3b, 0xa4, 0xab, 0x5b, 0x4a, 0xfa,
	0xe5, 0x26, 0x46, 0xc9, 0x80, 0x98, 0x05, 0xba, 0x51, 0x52, 0x44, 0x9f, 0xc1, 0x8a, 0x77, 0x43,
	0xbd, 0x5b, 0x1e, 0x0f, 0x74, 0x79, 0x2a, 0xf8, 0x48, 0x1b, 0xdc, 0xc9, 0x91, 0x04, 0xd2, 0xf7,
	0x54, 0xd3, 0x4e, 0x8a, 0x76, 0x0f, 0x56, 0x52, 0xbf, 0x29, 0x8d, 0x8c, 0x0c, 0x8d, 0x90, 0xad,
	0x99, 0x63, 0x2a, 0xe6, 0xac, 0x4e, 0xae, 0xc5, 0x53, 0xf6, 0xd8, 0x3b, 0x50, 0x90, 0x1a, 0x02,
	0x28, 0x5d, 0x9c, 0xb4, 0x5b, 0xfb, 0x5f, 0xd7, 0x73, 0x5a, 0xde, 0xdf, 0x6b, 0xd5, 0x0d, 0xfb,
	0x57, 0xd8, 0xba, 0xb3, 0xcd, 0x68, 0x17, 0x2a, 0x24, 0x65, 0xe3, 0x12, 0x7e, 0x4e, 0x0f, 0xd1,
	0x0b, 0x80, 0x68, 0x48, 0x19, 0x49, 0xca, 0x6c, 0xaa, 0x32, 0xd7, 0x71, 0x7a, 0x93, 0x32, 0x9f,
	0x0f, 0xdd, 0x8c, 0x8f, 0xfd, 0xaf, 0x09, 0x8f, 0xe7, 0xce, 0xd1, 0x2a, 0x98, 0x7e, 0x4f, 0xe7,
	0x68, 0xfa, 0x3d, 0xd4, 0x80, 0x15, 0x46, 0x47, 0x7e, 0x86, 0xfb, 0x13, 0x1d, 0x7d, 0xa1, 0x93,
	0xcf, 0xab, 0xb0, 0x9e, 0xcc, 0xbf, 0x85, 0x67, 0x27, 0xc8, 0x8b, 0x42, 0x21, 0x9b, 0x96, 0xd4,
	0x37, 0x55, 0xd1, 0x11, 0x54, 0xe9, 0x7b, 0xc1, 0x48, 0x32, 0xc4, 0x56, 0x51, 0xc5, 0xfd, 0x6c,
	0xe1, 0x2e, 0x67, 0xea, 0x93, 0xec, 0x8c, 0x2c, 0x4a, 0x46, 0xe9, 0x87, 0x82, 0xb2, 0x11, 0x09,
	0xac, 0x52, 0xd3, 0xd8, 0xcd, 0xbb, 0x13, 0xbd, 0xf1, 0x1d, 0xd4, 0xe7, 0xc1, 0x0f, 0xda, 0x12,
	0xcf, 0xa7, 0xed, 0x3b, 0x72, 0x9d, 0x76, 0xd7, 0x49, 0xda, 0x77, 0x76, 0xfe, 0xa6, 0x73, 0xfc,
	0x53, 0xdd, 0x90, 0xb2, 0xeb, 0x9c, 0x9d, 0x5f, 0x3a, 0x75, 0xd3, 0xde, 0x5a, 0x24, 0xad, 0x9e,
	0x3b, 0x1b, 0x41, 0xfd, 0x47, 0x4a, 0x87, 0xed, 0xc0, 0x1f, 0x51, 0x97, 0xfe, 0x12, 0x53, 0x2e,
	0xec, 0x75, 0x58, 0xcb, 0xd8, 0xf8, 0x30, 0x0a, 0x39, 0xb5, 0x2f, 0x61, 0xe5, 0x34, 0xea, 0x3b,
	0x23, 0x59, 0x9c, 0x0f, 0xef, 0x7e, 0x13, 0xaa, 0x3f, 0x73, 0x45, 0x1c, 0x55, 0xe4, 0x24, 0x8b,
	0xac, 0xc9, 0xde, 0x84, 0x8d, 0x77, 0x11, 0x17, 0xe9, 0xdd, 0x93, 0xf7, 0xbe, 0x82, 0x9a, 0xb4,
	0xd3, 0xde, 0x19, 0x15, 0xcc, 0xf7, 0xd0, 0x53, 0x28, 0x0d, 0x94, 0xa4, 0xc7, 0xab, 0x8c, 0x93,
	0x03, 0x57, 0x9b, 0xed, 0xb7, 0x50, 0xd2, 0xae, 0xaf, 0xa1, 0x16, 0x92, 0x01, 0xed, 0x92, 0xfe,
	0xe5, 0x64, 0x34, 0xaa, 0xad, 0x75, 0xfc, 0x36, 0x63, 0x4c, 0x5c, 0x4f, 0x72, 0xee, 0x8c, 0xab,
	0xdc, 0x1c, 0x23, 0xc2, 0x7c, 0x12, 0x0a, 0xfb, 0xaf, 0x02, 0xa0, 0x45, 0x84, 0x5c, 0xf6, 0x12,
	0xa1, 0x9b, 0xa4, 0x64, 0xb4, 0x0d, 0x15, 0xe1, 0x0f, 0x28, 0x17, 0x64, 0x30, 0x54, 0x39, 0xe6,
	0xdd, 0xa9, 0x01, 0xed, 0x41, 0x41, 0x90, 0x7e, 0xfa, 0xbd, 0xf9, 0x64, 0x49, 0x18, 0xb8, 0x4b,
	0xfa, 0x9a, 0x3f, 0xca, 0x15, 0x1d, 0x40, 0xf9, 0x5a, 0xb5, 0x9a, 0x5b, 0x05, 0x85, 0x6a, 0x2e,
	0x43, 0x1d, 0x27, 0x2e, 0x09, 0x30, 0x05, 0x48, 0x2c, 0xd7, 0xd8, 0xe2, 0xdd, 0xd8, 0x8b, 0x19,
	0x2c, 0x9f, 0x62, 0x7d, 0x8d, 0x2d, 0xdd, 0x8d, 0xed, 0xcc, 0x60, 0x35, 0xa0, 0xf1, 0x0d, 0x54,
	0x26, 0x69, 0x3c, 0x84, 0xc9, 0x8d, 0x03, 0xa8, 0x65, 0x33, 0xf9, 0x3f, 0xac, 0x31, 0x87, 0xbd,
	0x78, 0x00, 0x76, 0xfe, 0xdd, 0xce, 0x03, 0xb0, 0xf9, 0xec, 0xf4, 0x6d, 0x00, 0x92, 0xec, 0xd4,
	0x14, 0x4c, 0x39, 0xfb, 0xb7, 0x01, 0x1f, 0xdf, 0xf3, 0x99, 0x42, 0x9f, 0xc2, 0x23, 0x2f, 0x62,
	0x8c, 0x06, 0x6a, 0x7d, 0x74, 0xd2, 0x85, 0x36, 0x6b, 0x9c, 0x9d, 0x2e, 0xf3, 0xbe, 0xe9, 0xca,
	0xac, 0xaf, 0xfc, 0xec, 0xfa, 0xb2, 0xa0, 0x2c, 0x09, 0x18, 0xc5, 0xc9, 0x62, 0xcb, 0xbb, 0xa9,
	0x6a, 0xc7, 0x80, 0x32, 0x21, 0xb9, 0x94, 0xc7, 0x81, 0xe0, 0x1f, 0x18, 0xd9, 0x26, 0x94, 0x28,
	0x63, 0x11, 0x4b, 0xf6, 0x78, 0xc5, 0xd5, 0x1a, 0x7a, 0x06, 0xe5, 0x64, 0x08, 0x53, 0x92, 0x4f,
	0x86, 0x33, 0xb5, 0xdb, 0x4d, 0xd8, 0x91, 0x05, 0x5b, 0x7c, 0x3a, 0x2d, 0xde, 0xf3, 0xcf, 0xa1,
	0x32, 0x49, 0x12, 0xd5, 0x60, 0xa5, 0xeb, 0x9c, 0x3a, 0x3f, 0xb8, 0xed, 0xe3, 0x7a, 0x4e, 0x6a,
	0xc7, 0x9d, 0x53, 0xe7, 0xd0, 0x69, 0x77, 0xeb, 0x46, 0xeb, 0x1f, 0x13, 0xd6, 0xbb, 0xe9, 0xbf,
	0x63, 0x7b, 0x70, 0x45, 0x38, 0x27, 0xbd, 0x88, 0xa1, 0x97, 0x50, 0x6d, 0x0b, 0xf9, 0xa9, 0x57,
	0x2d, 0x40, 0x8f, 0x66, 0x7e, 0xec, 0x1a, 0x8b, 0x9f, 0x76, 0x3b, 0xf7, 0xc2, 0x40, 0xaf, 0xa0,
	0x32, 0xd9, 0x75, 0x68, 0x0d, 0xcf, 0xef, 0xc2, 0x06, 0xc2, 0x8b, 0xab, 0x30, 0x87, 0x5a, 0xc9,
	0x72, 0x9a, 0x2c, 0xc4, 0x0a, 0x4e, 0xc5, 0xc6, 0x13, 0xbc, 0x74, 0x9d, 0x49, 0x0c, 0x4c, 0x29,
	0x83, 0x1e, 0xe1, 0xec, 0x76, 0x6b, 0xac, 0xe3, 0x25, 0x74, 0xca, 0xa1, 0x77, 0xb0, 0xb9, 0xbc,
	0x6a, 0x68, 0x1d, 0x2f, 0x1a, 0x1b, 0x4f, 0xf1, 0xfd, 0x35, 0xb6, 0x73, 0x87, 0x3b, 0xb0, 0xed,
	0x45, 0x03, 0xcc, 0x88, 0x77, 0xcb, 0x87, 0xc4, 0xa3, 0x98, 0x93, 0x20, 0xe6, 0x98, 0x53, 0x36,
	0xf2, 0x3d, 0xca, 0xaf, 0x4a, 0xea, 0x37, 0xfc, 0xe5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x24, 0x81, 0xef, 0x9e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TelemetryAmbassadorClient is the client API for TelemetryAmbassador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TelemetryAmbassadorClient interface {
	AttachEnvoy(ctx context.Context, in *EnvoySummary, opts ...grpc.CallOption) (TelemetryAmbassador_AttachEnvoyClient, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	PostLogEvent(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*PostLogEventResponse, error)
	PostMetric(ctx context.Context, in *PostedMetric, opts ...grpc.CallOption) (*PostMetricResponse, error)
	PostTestMonitorResults(ctx context.Context, in *TestMonitorResults, opts ...grpc.CallOption) (*PostTestMonitorResultsResponse, error)
}

type telemetryAmbassadorClient struct {
	cc *grpc.ClientConn
}

func NewTelemetryAmbassadorClient(cc *grpc.ClientConn) TelemetryAmbassadorClient {
	return &telemetryAmbassadorClient{cc}
}

func (c *telemetryAmbassadorClient) AttachEnvoy(ctx context.Context, in *EnvoySummary, opts ...grpc.CallOption) (TelemetryAmbassador_AttachEnvoyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TelemetryAmbassador_serviceDesc.Streams[0], "/TelemetryAmbassador/AttachEnvoy", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryAmbassadorAttachEnvoyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelemetryAmbassador_AttachEnvoyClient interface {
	Recv() (*EnvoyInstruction, error)
	grpc.ClientStream
}

type telemetryAmbassadorAttachEnvoyClient struct {
	grpc.ClientStream
}

func (x *telemetryAmbassadorAttachEnvoyClient) Recv() (*EnvoyInstruction, error) {
	m := new(EnvoyInstruction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telemetryAmbassadorClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/TelemetryAmbassador/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAmbassadorClient) PostLogEvent(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*PostLogEventResponse, error) {
	out := new(PostLogEventResponse)
	err := c.cc.Invoke(ctx, "/TelemetryAmbassador/PostLogEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAmbassadorClient) PostMetric(ctx context.Context, in *PostedMetric, opts ...grpc.CallOption) (*PostMetricResponse, error) {
	out := new(PostMetricResponse)
	err := c.cc.Invoke(ctx, "/TelemetryAmbassador/PostMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAmbassadorClient) PostTestMonitorResults(ctx context.Context, in *TestMonitorResults, opts ...grpc.CallOption) (*PostTestMonitorResultsResponse, error) {
	out := new(PostTestMonitorResultsResponse)
	err := c.cc.Invoke(ctx, "/TelemetryAmbassador/PostTestMonitorResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryAmbassadorServer is the server API for TelemetryAmbassador service.
type TelemetryAmbassadorServer interface {
	AttachEnvoy(*EnvoySummary, TelemetryAmbassador_AttachEnvoyServer) error
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	PostLogEvent(context.Context, *LogEvent) (*PostLogEventResponse, error)
	PostMetric(context.Context, *PostedMetric) (*PostMetricResponse, error)
	PostTestMonitorResults(context.Context, *TestMonitorResults) (*PostTestMonitorResultsResponse, error)
}

// UnimplementedTelemetryAmbassadorServer can be embedded to have forward compatible implementations.
type UnimplementedTelemetryAmbassadorServer struct {
}

func (*UnimplementedTelemetryAmbassadorServer) AttachEnvoy(req *EnvoySummary, srv TelemetryAmbassador_AttachEnvoyServer) error {
	return status.Errorf(codes.Unimplemented, "method AttachEnvoy not implemented")
}
func (*UnimplementedTelemetryAmbassadorServer) KeepAlive(ctx context.Context, req *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (*UnimplementedTelemetryAmbassadorServer) PostLogEvent(ctx context.Context, req *LogEvent) (*PostLogEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostLogEvent not implemented")
}
func (*UnimplementedTelemetryAmbassadorServer) PostMetric(ctx context.Context, req *PostedMetric) (*PostMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMetric not implemented")
}
func (*UnimplementedTelemetryAmbassadorServer) PostTestMonitorResults(ctx context.Context, req *TestMonitorResults) (*PostTestMonitorResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTestMonitorResults not implemented")
}

func RegisterTelemetryAmbassadorServer(s *grpc.Server, srv TelemetryAmbassadorServer) {
	s.RegisterService(&_TelemetryAmbassador_serviceDesc, srv)
}

func _TelemetryAmbassador_AttachEnvoy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnvoySummary)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryAmbassadorServer).AttachEnvoy(m, &telemetryAmbassadorAttachEnvoyServer{stream})
}

type TelemetryAmbassador_AttachEnvoyServer interface {
	Send(*EnvoyInstruction) error
	grpc.ServerStream
}

type telemetryAmbassadorAttachEnvoyServer struct {
	grpc.ServerStream
}

func (x *telemetryAmbassadorAttachEnvoyServer) Send(m *EnvoyInstruction) error {
	return x.ServerStream.SendMsg(m)
}

func _TelemetryAmbassador_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAmbassador_PostLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).PostLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/PostLogEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).PostLogEvent(ctx, req.(*LogEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAmbassador_PostMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostedMetric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).PostMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/PostMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).PostMetric(ctx, req.(*PostedMetric))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAmbassador_PostTestMonitorResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMonitorResults)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).PostTestMonitorResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/PostTestMonitorResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).PostTestMonitorResults(ctx, req.(*TestMonitorResults))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelemetryAmbassador_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TelemetryAmbassador",
	HandlerType: (*TelemetryAmbassadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _TelemetryAmbassador_KeepAlive_Handler,
		},
		{
			MethodName: "PostLogEvent",
			Handler:    _TelemetryAmbassador_PostLogEvent_Handler,
		},
		{
			MethodName: "PostMetric",
			Handler:    _TelemetryAmbassador_PostMetric_Handler,
		},
		{
			MethodName: "PostTestMonitorResults",
			Handler:    _TelemetryAmbassador_PostTestMonitorResults_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachEnvoy",
			Handler:       _TelemetryAmbassador_AttachEnvoy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "telemetry-edge.proto",
}
